{% set name = "typenames" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/typenames-{{ version }}.tar.gz
  sha256: a694a19aecf5884b2c52cdf9a03b501bc7ee9a03131bfa58b2a6b072182270a7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - typing-extensions >4

test:
  imports:
    - typenames
  commands:
    - pip check
  requires:
    - pip

about:
  summary: String representations of Python type annotations.
  license: MIT
  license_file: LICENSE
  home: https://github.com/jayqi/typenames
  dev_url: https://github.com/jayqi/typenames
  doc_url: https://jayqi.github.io/typenames/

extra:
  recipe-maintainers:
    - jayqi
