{% set name = "typenames" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/typenames-{{ version }}.tar.gz
  sha256: 205a1954512e28b6558e761c134e74d243003755676fe8cce49250b8fc192798

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - typenames
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: String representations of Python type annotations.
  license: MIT
  license_file: LICENSE
  home: https://github.com/jayqi/typenames
  dev_url: https://github.com/jayqi/typenames
  doc_url: https://jayqi.github.io/typenames/

extra:
  recipe-maintainers:
    - jayqi
